version: 2.1

default_steps: &default_steps
  steps:
    - checkout
    - run: sudo gem update --system
    - run: bundle install && npm install
    - run: npx percy exec -- bundle exec rake test

jobs:
  test:
    # This is the one environment where we'll capture and upload snapshots in CI.
    docker:
      - image: circleci/ruby:2.7-node-browsers
    <<: *default_steps

workflows:
  version: 2
  test:
    jobs:
      - test
